apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote-svc
  name: vote-svc
  namespace: vote
spec:
  ports:
  - name: 5000-80
    nodePort: 31000
    port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: vote
  type: NodePort
status:
  loadBalancer: {}
